version: '2'
services:

  hive:
    image: kliew/hive-dev
    container_name: "hive"
    ports:
      - "9999:9999"
    volumes:
      - "./data/csv:/data"
      - "./hive:/hive_init"
  
  mongo:
    image: mongo
    container_name: "mongo"
    volumes:
      - "./data/json:/data"
      - "./mongo:/mongo_init"
  
  mongoui:
    image: mongo-express
    external_links:
      - mongodb
    ports:
      - "8081:8081"
